### ISSUE TITLE
`getResources` could return the invalid iterator

### ISSUE THREAD

**Issue by nemanja-boric-sociomantic** [sociomantic-tsunami/dhtnode#12]
When shutting down and starting up `neotest` utility in the mirror mode (starting and shutting down several instances at random times, while three to four `neotest` instances are filling the channels, dhtnode segfaulted.

It seems that the iterator returned here:

https://github.com/sociomantic-tsunami/dhtnode/blob/neo/src/dhtnode/request/neo/Mirror.d#L198

is invalid:

```
(gdb) p *iterator
$6 = {storage = 0x7ffff2d09dd8, started = 8, 
  key_buffer = 0x1 <error: Cannot access memory at address 0x1>, 
  current_key = 0x8 <error: Cannot access memory at address 0x8>, 
  value_buffer = 0x8 <error: Cannot access memory at address 0x8>}
```

```
#0  0x0000000000000000 in ?? ()
#1  0x0000000000671ea7 in dhtnode.request.neo.Mirror.MirrorImpl_v0.startIteration() (this=0x7ffff2a94d78)
    at ./src/dhtnode/request/neo/Mirror.d:199
#2  0x0000000000688814 in dhtproto.node.neo.request.Mirror.MirrorProtocol_v0.PeriodicRefresh.refresh() (this=0x7ffff2a94be0)
    at ./submodules/dhtproto/src/dhtproto/node/neo/request/Mirror.d:979
#3  0x0000000000688766 in dhtproto.node.neo.request.Mirror.MirrorProtocol_v0.PeriodicRefresh.fiberMethod() (this=0x7ffff2a94be0)
    at ./submodules/dhtproto/src/dhtproto/node/neo/request/Mirror.d:964
#4  0x0000000000769d9e in core.thread.Fiber.run() (
    this=0x7ffff2a94d68)
    at /home/jenkins/docker/src/core/thread.d:3200
#5  0x0000000000769cf8 in fiber_entryPoint ()
    at /home/jenkins/docker/src/core/thread.d:2489
#6  0x0000000000000000 in ?? ()
```

**Comment by nemanja-boric-sociomantic** [comment]
It looks like this is a classic example of the zombie timers. It's hard to reproduce, but it seems it's happening when you shutdown the client doing the mirror request and the refresh cycle kicks in.

**Comment by gavin-norman-sociomantic** [comment]
As a workaround, you could try replacing https://github.com/sociomantic-tsunami/dhtnode/blob/neo/src/dhtnode/connection/neo/SharedResources.d#L222-L226 with
```D
        public StorageEngineStepIterator getIterator ( )
        {
            return new StorageEngineStepIterator;
}
```

**Comment by gavin-norman-sociomantic** [comment]
I suspect this is fixed by https://github.com/sociomantic-tsunami/dhtproto/pull/26. Let's see if it happens again.

**Comment by nemanja-boric-sociomantic** [comment]
I'll test it again now.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, looks fixed :+1:
